2020-12-01 07:26:48,570 INFO flask.app MainThread: DefectCode Loading
2020-12-01 08:12:01,139 INFO flask.app MainThread: DefectCode Loading
2020-12-01 08:15:38,891 ERROR flask.app MainThread: Exception on /api/annotator/data [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/workspace/webserver/util/__init__.py", line 10, in wrap
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/annotator.py", line 54, in post
    self.write_back_to_shared_folder(labelme_document, aggregate)
  File "/workspace/webserver/api/annotator.py", line 70, in write_back_to_shared_folder
    file_directory = current_user.get_shared_folder_with(aggregate.get_stripID()).get_mount_directory(aggregate.get_dataset_name())
  File "/workspace/database/users.py", line 189, in get_shared_folder_with
    raise ValueError(err_msg)
ValueError: Given stripID:  is invalid
2020-12-01 08:19:29,594 INFO flask.app MainThread: DefectCode Loading
2020-12-01 08:19:38,768 INFO flask.app MainThread: DefectCode Loading
2020-12-01 08:19:45,581 INFO flask.app MainThread: Annotation Change Saved
2020-12-01 08:19:45,778 INFO flask.app MainThread: DefectCode Loading
2020-12-01 08:19:48,008 INFO flask.app MainThread: DefectCode Loading
2020-12-01 08:20:08,662 ERROR flask.app MainThread: Exception on /api/annotator/data [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/workspace/webserver/util/__init__.py", line 10, in wrap
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/annotator.py", line 54, in post
    self.write_back_to_shared_folder(labelme_document, aggregate)
  File "/workspace/webserver/api/annotator.py", line 70, in write_back_to_shared_folder
    file_directory = current_user.get_shared_folder_with(aggregate.get_stripID()).get_mount_directory(aggregate.get_dataset_name())
  File "/workspace/database/users.py", line 189, in get_shared_folder_with
    raise ValueError(err_msg)
ValueError: Given stripID:  is invalid
2020-12-01 08:20:14,265 ERROR flask.app MainThread: Exception on /api/annotator/data [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/workspace/webserver/util/__init__.py", line 10, in wrap
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/annotator.py", line 54, in post
    self.write_back_to_shared_folder(labelme_document, aggregate)
  File "/workspace/webserver/api/annotator.py", line 70, in write_back_to_shared_folder
    file_directory = current_user.get_shared_folder_with(aggregate.get_stripID()).get_mount_directory(aggregate.get_dataset_name())
  File "/workspace/database/users.py", line 189, in get_shared_folder_with
    raise ValueError(err_msg)
ValueError: Given stripID:  is invalid
2020-12-01 08:20:22,989 INFO flask.app MainThread: DefectCode Loading
2020-12-01 08:20:29,856 INFO flask.app MainThread: Annotation Change Saved
2020-12-01 08:20:29,870 INFO flask.app MainThread: DefectCode Loading
2020-12-01 08:38:57,670 INFO flask.app MainThread: DefectCode Loading
2020-12-01 08:39:19,232 INFO flask.app MainThread: DefectCode Loading
2020-12-01 08:39:26,176 INFO flask.app MainThread: DefectCode Loading
2020-12-01 08:39:39,774 INFO flask.app MainThread: DefectCode Loading
2020-12-01 09:40:47,936 INFO flask.app MainThread: DefectCode Loading
2020-12-01 09:40:55,921 INFO flask.app MainThread: DefectCode Loading
2020-12-01 09:41:05,591 INFO flask.app MainThread: DefectCode Loading
2020-12-01 09:45:00,429 INFO flask.app MainThread: DefectCode Loading
2020-12-02 01:19:50,173 INFO flask.app MainThread: DefectCode Loading
2020-12-02 01:20:49,553 INFO flask.app MainThread: DefectCode Loading
2020-12-02 01:27:48,723 INFO flask.app MainThread: DefectCode Loading
2020-12-02 01:47:00,094 INFO flask.app MainThread: DefectCode Loading
2020-12-02 01:47:11,829 INFO flask.app MainThread: DefectCode Loading
2020-12-02 01:47:58,062 INFO flask.app MainThread: DefectCode Loading
2020-12-02 01:48:27,828 INFO flask.app MainThread: DefectCode Loading
2020-12-02 01:52:31,260 INFO flask.app MainThread: DefectCode Loading
2020-12-02 01:52:59,276 INFO flask.app MainThread: DefectCode Loading
2020-12-02 01:53:20,312 INFO flask.app MainThread: DefectCode Loading
2020-12-02 01:55:28,317 INFO flask.app MainThread: DefectCode Loading
2020-12-02 01:58:28,203 INFO flask.app MainThread: DefectCode Loading
2020-12-02 01:58:37,138 INFO flask.app MainThread: DefectCode Loading
2020-12-02 03:10:35,898 INFO flask.app MainThread: DefectCode Loading
2020-12-02 03:48:36,106 INFO flask.app MainThread: DefectCode Loading
2020-12-02 03:49:14,821 INFO flask.app MainThread: DefectCode Loading
2020-12-02 03:49:38,745 INFO flask.app MainThread: DefectCode Loading
2020-12-02 03:52:06,676 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:16:23,536 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:16:39,690 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:30:20,439 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:30:32,346 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:30:40,820 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:31:31,115 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:31:46,872 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:33:43,003 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:33:55,652 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:35:43,555 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:36:37,461 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:36:41,662 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:36:59,066 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:40:15,883 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:48:47,365 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:48:51,985 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:49:30,387 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:49:44,713 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:50:23,730 INFO flask.app MainThread: DefectCode Loading
2020-12-02 06:50:43,710 INFO flask.app MainThread: DefectCode Loading
2020-12-02 07:02:28,767 INFO flask.app MainThread: DefectCode Loading
2020-12-02 07:20:15,154 INFO flask.app MainThread: DefectCode Loading
2020-12-02 07:20:24,798 INFO flask.app MainThread: DefectCode Loading
2020-12-02 07:20:31,201 INFO flask.app MainThread: DefectCode Loading
2020-12-02 08:01:09,101 INFO flask.app MainThread: DefectCode Loading
2020-12-02 08:02:37,959 INFO flask.app MainThread: DefectCode Loading
2020-12-02 08:03:04,157 INFO flask.app MainThread: DefectCode Loading
2020-12-02 08:03:39,635 INFO flask.app MainThread: DefectCode Loading
2020-12-02 08:04:02,262 INFO flask.app MainThread: DefectCode Loading
2020-12-02 08:04:21,261 INFO flask.app MainThread: DefectCode Loading
2020-12-02 08:07:20,203 INFO flask.app MainThread: DefectCode Loading
2020-12-02 08:07:29,069 ERROR flask.app MainThread: Exception on /api/annotator/data [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/workspace/webserver/util/__init__.py", line 10, in wrap
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/annotator.py", line 54, in post
    self.write_back_to_shared_folder(labelme_document, aggregate)
  File "/workspace/webserver/api/annotator.py", line 70, in write_back_to_shared_folder
    file_directory = current_user.get_shared_folder_with(aggregate.get_stripID()).get_mount_directory(aggregate.get_dataset_name())
  File "/workspace/database/users.py", line 189, in get_shared_folder_with
    raise ValueError(err_msg)
ValueError: Given stripID:  is invalid
2020-12-02 08:20:16,411 INFO flask.app MainThread: DefectCode Loading
2020-12-02 08:46:58,291 INFO flask.app MainThread: DefectCode Loading
2020-12-03 02:04:15,285 INFO flask.app MainThread: DefectCode Loading
2020-12-03 02:04:22,149 INFO flask.app MainThread: DefectCode Loading
2020-12-03 02:07:52,522 INFO flask.app MainThread: DefectCode Loading
2020-12-03 02:08:54,368 ERROR flask.app MainThread: Exception on /api/image/1208 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/images.py", line 135, in get
    pil_image = image.open_thumbnail() if thumbnail else Image.open(image.path)
  File "/workspace/database/images.py", line 157, in open_thumbnail
    return Image.open(thumbnail_path)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/stripID_2/logcaseR1/.thumbnail/gray.png'
2020-12-03 02:08:54,493 ERROR flask.app MainThread: Exception on /api/image/1207 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/images.py", line 135, in get
    pil_image = image.open_thumbnail() if thumbnail else Image.open(image.path)
  File "/workspace/database/images.py", line 157, in open_thumbnail
    return Image.open(thumbnail_path)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/stripID_2/logcaseR1/.thumbnail/rgb.png'
2020-12-03 02:08:54,936 INFO flask.app MainThread: DefectCode Loading
2020-12-03 02:08:59,154 INFO flask.app MainThread: DefectCode Loading
2020-12-03 02:08:59,174 INFO flask.app MainThread: Annotation Change Saved
2020-12-03 02:09:07,114 INFO flask.app MainThread: DefectCode Loading
2020-12-03 02:18:19,436 INFO flask.app MainThread: DefectCode Loading
2020-12-03 02:18:51,288 INFO flask.app MainThread: DefectCode Loading
2020-12-03 02:19:08,000 INFO flask.app MainThread: DefectCode Loading
2020-12-03 02:19:31,199 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:21:47,815 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:30:16,629 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:30:17,535 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:30:38,428 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:30:48,510 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:31:21,717 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:32:33,722 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:34:34,201 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:36:24,742 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:36:44,716 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:36:59,711 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:37:15,775 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:38:58,788 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:39:27,907 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:39:55,035 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:40:01,638 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:42:23,841 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:43:04,624 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:43:17,766 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:43:43,269 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:44:09,387 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:44:53,480 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:45:06,830 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:45:45,277 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:45:59,685 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:46:21,778 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:46:27,116 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:48:29,435 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:49:31,417 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:50:49,365 INFO flask.app MainThread: DefectCode Loading
2020-12-03 06:54:47,984 INFO flask.app MainThread: DefectCode Loading
2020-12-03 07:06:08,532 INFO flask.app MainThread: DefectCode Loading
2020-12-03 07:25:29,932 INFO flask.app MainThread: DefectCode Loading
2020-12-03 07:25:39,779 INFO flask.app MainThread: DefectCode Loading
2020-12-03 07:26:42,220 INFO flask.app MainThread: DefectCode Loading
2020-12-03 07:36:47,359 INFO flask.app MainThread: DefectCode Loading
2020-12-03 07:38:55,259 INFO flask.app MainThread: DefectCode Loading
2020-12-03 07:40:12,140 INFO flask.app MainThread: DefectCode Loading
2020-12-03 07:41:11,638 INFO flask.app MainThread: DefectCode Loading
2020-12-03 08:50:33,313 INFO flask.app MainThread: DefectCode Loading
2020-12-03 08:53:14,102 INFO flask.app MainThread: DefectCode Loading
2020-12-03 08:53:35,414 INFO flask.app MainThread: DefectCode Loading
2020-12-03 08:59:05,710 INFO flask.app MainThread: DefectCode Loading
2020-12-03 08:59:53,060 ERROR flask.app MainThread: Exception on /api/image/1208 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/images.py", line 135, in get
    pil_image = image.open_thumbnail() if thumbnail else Image.open(image.path)
  File "/workspace/database/images.py", line 157, in open_thumbnail
    return Image.open(thumbnail_path)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/stripID_2/logcaseR1/.thumbnail/gray.png'
2020-12-03 08:59:53,242 ERROR flask.app MainThread: Exception on /api/image/1207 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/images.py", line 135, in get
    pil_image = image.open_thumbnail() if thumbnail else Image.open(image.path)
  File "/workspace/database/images.py", line 157, in open_thumbnail
    return Image.open(thumbnail_path)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/stripID_2/logcaseR1/.thumbnail/rgb.png'
2020-12-03 08:59:53,762 INFO flask.app MainThread: DefectCode Loading
2020-12-03 08:59:57,155 INFO flask.app MainThread: Annotation Change Saved
2020-12-03 08:59:57,230 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:00:05,717 INFO flask.app MainThread: Annotation Change Saved
2020-12-03 09:00:05,744 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:00:15,787 INFO flask.app MainThread: Annotation Change Saved
2020-12-03 09:00:15,837 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:00:34,280 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:00:40,508 ERROR flask.app MainThread: Exception on /api/image/1208 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/images.py", line 135, in get
    pil_image = image.open_thumbnail() if thumbnail else Image.open(image.path)
  File "/workspace/database/images.py", line 157, in open_thumbnail
    return Image.open(thumbnail_path)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/stripID_2/logcaseR1/.thumbnail/gray.png'
2020-12-03 09:00:40,562 ERROR flask.app MainThread: Exception on /api/image/1207 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/images.py", line 135, in get
    pil_image = image.open_thumbnail() if thumbnail else Image.open(image.path)
  File "/workspace/database/images.py", line 157, in open_thumbnail
    return Image.open(thumbnail_path)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/stripID_2/logcaseR1/.thumbnail/rgb.png'
2020-12-03 09:00:42,087 ERROR flask.app MainThread: Exception on /api/image/1207 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/images.py", line 135, in get
    pil_image = image.open_thumbnail() if thumbnail else Image.open(image.path)
  File "/workspace/database/images.py", line 157, in open_thumbnail
    return Image.open(thumbnail_path)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/stripID_2/logcaseR1/.thumbnail/rgb.png'
2020-12-03 09:00:42,168 ERROR flask.app MainThread: Exception on /api/image/1208 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/images.py", line 135, in get
    pil_image = image.open_thumbnail() if thumbnail else Image.open(image.path)
  File "/workspace/database/images.py", line 157, in open_thumbnail
    return Image.open(thumbnail_path)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/stripID_2/logcaseR1/.thumbnail/gray.png'
2020-12-03 09:00:42,934 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:01:19,405 ERROR flask.app MainThread: Exception on /api/annotator/data [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/workspace/webserver/util/__init__.py", line 10, in wrap
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/annotator.py", line 54, in post
    self.write_back_to_shared_folder(labelme_document, aggregate)
  File "/workspace/webserver/api/annotator.py", line 70, in write_back_to_shared_folder
    file_directory = current_user.get_shared_folder_with(aggregate.get_stripID()).get_mount_directory(aggregate.get_dataset_name())
  File "/workspace/database/users.py", line 189, in get_shared_folder_with
    raise ValueError(err_msg)
ValueError: Given stripID:  is invalid
2020-12-03 09:01:23,451 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:01:32,338 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:01:46,163 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:01:50,013 ERROR flask.app MainThread: Exception on /api/annotator/data [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/workspace/webserver/util/__init__.py", line 10, in wrap
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/annotator.py", line 54, in post
    self.write_back_to_shared_folder(labelme_document, aggregate)
  File "/workspace/webserver/api/annotator.py", line 70, in write_back_to_shared_folder
    file_directory = current_user.get_shared_folder_with(aggregate.get_stripID()).get_mount_directory(aggregate.get_dataset_name())
  File "/workspace/database/users.py", line 189, in get_shared_folder_with
    raise ValueError(err_msg)
ValueError: Given stripID:  is invalid
2020-12-03 09:01:53,421 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:02:04,240 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:03:10,260 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:03:12,157 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:03:13,754 ERROR flask.app MainThread: Exception on /api/annotator/data [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/workspace/webserver/util/__init__.py", line 10, in wrap
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/annotator.py", line 54, in post
    self.write_back_to_shared_folder(labelme_document, aggregate)
  File "/workspace/webserver/api/annotator.py", line 70, in write_back_to_shared_folder
    file_directory = current_user.get_shared_folder_with(aggregate.get_stripID()).get_mount_directory(aggregate.get_dataset_name())
  File "/workspace/database/users.py", line 189, in get_shared_folder_with
    raise ValueError(err_msg)
ValueError: Given stripID:  is invalid
2020-12-03 09:03:27,017 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:03:32,304 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:03:47,903 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:03:53,183 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:04:01,100 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:04:03,243 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:04:11,199 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:04:19,502 ERROR flask.app MainThread: Exception on /api/annotator/data [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/workspace/webserver/util/__init__.py", line 10, in wrap
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/annotator.py", line 54, in post
    self.write_back_to_shared_folder(labelme_document, aggregate)
  File "/workspace/webserver/api/annotator.py", line 70, in write_back_to_shared_folder
    file_directory = current_user.get_shared_folder_with(aggregate.get_stripID()).get_mount_directory(aggregate.get_dataset_name())
  File "/workspace/database/users.py", line 189, in get_shared_folder_with
    raise ValueError(err_msg)
ValueError: Given stripID:  is invalid
2020-12-03 09:04:22,151 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:04:36,484 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:05:02,253 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:14:05,904 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:14:11,157 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:14:24,770 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:15:50,788 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:15:57,477 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:15:59,787 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:16:12,287 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:16:15,707 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:17:08,640 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:17:11,481 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:17:13,170 ERROR flask.app MainThread: Exception on /api/annotator/data [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/workspace/webserver/util/__init__.py", line 10, in wrap
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/annotator.py", line 54, in post
    self.write_back_to_shared_folder(labelme_document, aggregate)
  File "/workspace/webserver/api/annotator.py", line 70, in write_back_to_shared_folder
    file_directory = current_user.get_shared_folder_with(aggregate.get_stripID()).get_mount_directory(aggregate.get_dataset_name())
  File "/workspace/database/users.py", line 189, in get_shared_folder_with
    raise ValueError(err_msg)
ValueError: Given stripID:  is invalid
2020-12-03 09:17:13,964 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:17:21,306 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:17:53,783 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:17:57,998 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:18:11,636 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:18:47,897 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:19:03,409 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:19:14,840 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:19:17,795 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:19:29,292 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:21:13,473 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:21:18,128 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:21:37,698 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:21:44,185 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:21:48,536 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:21:53,347 INFO flask.app MainThread: DefectCode Loading
2020-12-03 09:22:07,255 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:04:38,794 ERROR flask.app MainThread: Exception on /api/image/1208 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/images.py", line 135, in get
    pil_image = image.open_thumbnail() if thumbnail else Image.open(image.path)
  File "/workspace/database/images.py", line 157, in open_thumbnail
    return Image.open(thumbnail_path)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/stripID_2/logcaseR1/.thumbnail/gray.png'
2020-12-04 02:04:38,842 ERROR flask.app MainThread: Exception on /api/image/1207 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/images.py", line 135, in get
    pil_image = image.open_thumbnail() if thumbnail else Image.open(image.path)
  File "/workspace/database/images.py", line 157, in open_thumbnail
    return Image.open(thumbnail_path)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/stripID_2/logcaseR1/.thumbnail/rgb.png'
2020-12-04 02:04:40,117 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:04:52,864 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:05:00,179 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:18:59,974 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:22:08,510 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:23:11,709 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:28:31,989 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:29:12,464 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:29:30,811 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:29:37,295 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:29:51,357 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:30:03,917 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:31:14,108 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:31:28,340 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:32:51,238 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:36:42,055 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:36:50,409 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:37:48,098 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:45:53,061 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:49:41,310 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:52:54,788 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:53:48,907 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:54:18,740 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:54:28,783 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:55:22,544 ERROR flask.app MainThread: Exception on /api/image/1207 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/images.py", line 135, in get
    pil_image = image.open_thumbnail() if thumbnail else Image.open(image.path)
  File "/workspace/database/images.py", line 157, in open_thumbnail
    return Image.open(thumbnail_path)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/stripID_2/logcaseR1/.thumbnail/rgb.png'
2020-12-04 02:55:22,561 ERROR flask.app MainThread: Exception on /api/image/1208 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/images.py", line 135, in get
    pil_image = image.open_thumbnail() if thumbnail else Image.open(image.path)
  File "/workspace/database/images.py", line 157, in open_thumbnail
    return Image.open(thumbnail_path)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/stripID_2/logcaseR1/.thumbnail/gray.png'
2020-12-04 02:55:22,851 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:55:58,151 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:56:01,172 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:57:04,607 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:57:05,158 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:57:05,328 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:57:05,519 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:57:05,691 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:57:05,866 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:57:06,036 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:58:12,080 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:58:20,183 INFO flask.app MainThread: DefectCode Loading
2020-12-04 02:58:39,900 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:02:24,082 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:02:48,125 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:04:07,108 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:08:19,046 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:08:31,905 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:08:37,174 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:11:31,332 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:14:29,062 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:16:03,210 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:16:52,483 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:17:32,256 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:21:00,046 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:21:14,203 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:21:21,070 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:24:15,996 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:24:23,777 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:25:22,912 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:25:40,424 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:25:51,629 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:31:32,088 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:33:00,172 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:38:27,492 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:38:36,530 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:42:40,322 INFO flask.app MainThread: DefectCode Loading
2020-12-04 03:42:47,878 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:15:15,303 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:27:17,872 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:28:24,779 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:33:26,474 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:33:38,018 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:34:15,053 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:37:21,921 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:40:43,224 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:41:31,963 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:41:38,859 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:43:08,775 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:43:34,338 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:43:49,785 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:43:50,860 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:43:55,991 INFO flask.app MainThread: Change the metadata of the annotation to Wire Trace No Wire
2020-12-04 06:43:57,625 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:44:37,896 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:44:50,142 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:45:07,815 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:47:00,727 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:49:10,945 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:50:50,755 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:51:43,547 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:52:09,991 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:53:24,293 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:58:09,189 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:58:27,002 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:58:54,037 INFO flask.app MainThread: DefectCode Loading
2020-12-04 06:59:13,468 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:12:54,336 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:17:04,284 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:19:15,378 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:19:48,482 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:21:25,257 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:23:01,325 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:24:31,858 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:29:01,302 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:30:12,490 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:31:15,352 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:33:35,523 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:34:31,527 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:34:48,508 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:35:00,765 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:37:12,451 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:40:53,246 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:41:06,876 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:43:23,224 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:44:50,013 INFO flask.app MainThread: DefectCode Loading
2020-12-04 07:44:59,435 INFO flask.app MainThread: DefectCode Loading
2020-12-04 08:32:45,413 INFO flask.app MainThread: DefectCode Loading
2020-12-04 08:32:59,459 INFO flask.app MainThread: DefectCode Loading
2020-12-04 08:34:12,570 INFO flask.app MainThread: DefectCode Loading
2020-12-04 08:36:52,115 INFO flask.app MainThread: DefectCode Loading
2020-12-04 08:37:07,486 INFO flask.app MainThread: DefectCode Loading
2020-12-04 08:37:14,606 INFO flask.app MainThread: DefectCode Loading
2020-12-04 08:37:21,088 INFO flask.app MainThread: DefectCode Loading
2020-12-04 08:37:33,350 INFO flask.app MainThread: DefectCode Loading
2020-12-04 08:42:12,125 INFO flask.app MainThread: DefectCode Loading
2020-12-04 08:44:35,704 INFO flask.app MainThread: DefectCode Loading
2020-12-04 08:44:44,947 INFO flask.app MainThread: DefectCode Loading
2020-12-04 08:45:39,410 INFO flask.app MainThread: DefectCode Loading
2020-12-07 02:10:43,284 ERROR flask.app MainThread: Exception on /api/image/1207 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/images.py", line 135, in get
    pil_image = image.open_thumbnail() if thumbnail else Image.open(image.path)
  File "/workspace/database/images.py", line 157, in open_thumbnail
    return Image.open(thumbnail_path)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/stripID_2/logcaseR1/.thumbnail/rgb.png'
2020-12-07 02:10:43,312 ERROR flask.app MainThread: Exception on /api/image/1208 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/images.py", line 135, in get
    pil_image = image.open_thumbnail() if thumbnail else Image.open(image.path)
  File "/workspace/database/images.py", line 157, in open_thumbnail
    return Image.open(thumbnail_path)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/stripID_2/logcaseR1/.thumbnail/gray.png'
2020-12-07 02:10:43,649 INFO flask.app MainThread: DefectCode Loading
2020-12-07 02:10:51,304 INFO flask.app MainThread: DefectCode Loading
2020-12-07 02:13:33,649 INFO flask.app MainThread: DefectCode Loading
2020-12-07 02:14:43,966 INFO flask.app MainThread: DefectCode Loading
2020-12-07 02:17:35,625 INFO flask.app MainThread: DefectCode Loading
2020-12-07 02:17:58,742 INFO flask.app MainThread: DefectCode Loading
2020-12-07 02:18:05,062 INFO flask.app MainThread: DefectCode Loading
2020-12-07 02:21:53,282 INFO flask.app MainThread: DefectCode Loading
2020-12-07 02:22:02,067 INFO flask.app MainThread: DefectCode Loading
